from __future__ import annotations

import json
import re

import httpx

from .base import AiProviderClient, AiResponse


class MockProvider(AiProviderClient):
    name = "mock"

    async def send_prompt(self, task: str, context: str) -> AiResponse:
        # Produce a deterministic stub edit so the MVP works without API keys.
        target = "index.js"
        match = re.search(r"file[:\s]+([\\w./-]+)", task, re.I)
        if match:
            target = match.group(1)

        content = f"""I'll update `{target}` based on your request.

```{target}
// Generated by Mock AI (no API key configured)
// Task: {task[:180].replace(chr(96), "'")}

const http = require("http");
const port = process.env.PORT || 3000;
const html = `<!doctype html><html><body style="font-family:Georgia,serif;padding:2rem;background:#0f172a;color:#e2e8f0">
  <h1 style="color:#38bdf8">Mock AI Build</h1>
  <p>{task.replace('`', "'")[:240]}</p>
</body></html>`;

if (process.env.FORGELINK_ONCE === "1") {{
  process.stdout.write(html);
  process.exit(0);
}}

const server = http.createServer((req, res) => {{
  res.writeHead(200, {{ "Content-Type": "text/html; charset=utf-8" }});
  res.end(html);
}});

server.listen(port, () => console.log(`listening on ${{port}}`));
```

Explanation: This mock provider simulates a coding agent so you can exercise the full workspace → route → write → sandbox loop without real keys.
"""
        return AiResponse(content=content, provider=self.name, model="mock-v1")


class ClaudeProvider(AiProviderClient):
    name = "claude"

    def __init__(self, api_key: str, model: str = "claude-sonnet-4-20250514"):
        self.api_key = api_key
        self.model = model

    async def send_prompt(self, task: str, context: str) -> AiResponse:
        headers = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
        payload = {
            "model": self.model,
            "max_tokens": 4096,
            "system": (
                "You are a senior software engineer collaborating in a shared Node.js workspace. "
                "When proposing file changes, wrap each file in a fenced code block whose language "
                "tag is the exact file path (example: ```index.js). Keep responses concise."
            ),
            "messages": [
                {
                    "role": "user",
                    "content": f"## Shared project context\n{context}\n\n## Task\n{task}",
                }
            ],
        }
        async with httpx.AsyncClient(timeout=90.0) as client:
            resp = await client.post("https://api.anthropic.com/v1/messages", headers=headers, json=payload)
            resp.raise_for_status()
            data = resp.json()
        text = "".join(block.get("text", "") for block in data.get("content", []) if block.get("type") == "text")
        return AiResponse(content=text, provider=self.name, model=self.model, raw=data)


class OpenAIProvider(AiProviderClient):
    name = "gpt"

    def __init__(self, api_key: str, model: str = "gpt-4o-mini"):
        self.api_key = api_key
        self.model = model

    async def send_prompt(self, task: str, context: str) -> AiResponse:
        headers = {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are a coding agent in a shared Node.js workspace. "
                        "Propose file edits using fenced blocks tagged with the file path."
                    ),
                },
                {"role": "user", "content": f"## Shared project context\n{context}\n\n## Task\n{task}"},
            ],
        }
        async with httpx.AsyncClient(timeout=90.0) as client:
            resp = await client.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload)
            resp.raise_for_status()
            data = resp.json()
        text = data["choices"][0]["message"]["content"]
        return AiResponse(content=text, provider=self.name, model=self.model, raw=data)


class GeminiProvider(AiProviderClient):
    name = "gemini"

    def __init__(self, api_key: str, model: str = "gemini-2.0-flash"):
        self.api_key = api_key
        self.model = model

    async def send_prompt(self, task: str, context: str) -> AiResponse:
        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent"
            f"?key={self.api_key}"
        )
        payload = {
            "contents": [
                {
                    "parts": [
                        {
                            "text": (
                                "You are a UI-focused coding agent in a shared Node.js workspace. "
                                "Propose file edits using fenced blocks tagged with the file path.\n\n"
                                f"## Shared project context\n{context}\n\n## Task\n{task}"
                            )
                        }
                    ]
                }
            ]
        }
        async with httpx.AsyncClient(timeout=90.0) as client:
            resp = await client.post(url, json=payload)
            resp.raise_for_status()
            data = resp.json()
        text = data["candidates"][0]["content"]["parts"][0]["text"]
        return AiResponse(content=text, provider=self.name, model=self.model, raw=data)


def parse_file_blocks(markdown: str) -> dict[str, str]:
    """Extract ```path ... ``` code blocks from model output."""
    pattern = re.compile(r"```([^\n`]+)\n(.*?)```", re.DOTALL)
    files: dict[str, str] = {}
    for lang, body in pattern.findall(markdown):
        path = lang.strip().split()[0]
        # Skip plain language tags without path separators or extensions
        if "/" in path or "." in path:
            files[path.lstrip("./")] = body.strip("\n") + ("\n" if body.strip() else "")
    return files
